config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'note' => 'note#index', as: 'notes'
  get 'photo' => 'photo#index', as: 'photos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/note_controller.rb
class NoteController < ApplicationController
  def index
  end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/home/index.html.erb
<header id="header">
  <div class="p-header__content">
    <h1 class="p-header__site-name c-font-hide">CatEye.note</h1>
    <ul class="p-header__nav">
      <li class="p-header__nav-menu c-font-hide"><a href="#">About</a></li>
      <li class="p-header__nav-menu c-font-hide"><a href="#">News</a></li>
      <li class="p-header__nav-menu c-font-hide"><a href="#">Site</a></li>
      <li class="p-header__nav-menu c-font-hide"><a href="#">Photo</a></li>
      <li class="p-header__nav-menu c-font-hide"><a href="#">Contact</a></li>
    </ul>
  </div>
</header>

<section id="main-visual">
  <div class="p-main-visual__content">
    <div class="p-main-visual__image-wrap">
      <img class="p-main-visual__image" src="<%= image_path("main-visual.jpg") %>" >
    </div>
    <div class="p-main-visual__catch-wrap">
      <h2 class="p-main-visual__catch">日常生活の、<br>記録と雑記。</h2>
      <p class="p-main-visual__site-name c-font-hide">CatEye.note</p>
      <div class="c-border-line--white"></div>
      <p class="p-main-visual__read-text">
        石川県在住の新人エンジニアが<br>
        作成したサイトです。<br>
        <br>
        日常生活での雑記、撮影した写真<br>
        を残していきます。<br>
        <br>
        興味・関心が得られるものが<br>
        あれば嬉しいです。<br>
        のんびりご覧ください。<br>
      </p>
    </div>
  </div>
</section>

<section id="news">
  <div class="p-news__content c-content-width">
    <div class="p-news__content-wrap">
      <div class="c-section-title__content news__section-title">
        <p class="c-section-title__decoration">お知らせ</p>
        <h3 class="c-section-title c-font-hide">NEWS</h3>
      </div>
      <div class="p-news__wrap">
        <div class="p-news__info-wrap">
          <div class="p-news__info">
            <p class="p-news__date c-font-hide c-read-text-color">2020.07.01</p>
            <p class="p-news__tag">更新情報</p>
            <p class="p-news__title c-read-text-color">このサイトをリリースしました。</p>
          </div>
          <div class="c-read-text-color">+</div>
        </div>
        <p class="p-news__note">このサイトをリリースしました。リリースに当たるまでの経緯はこちらをご覧ください</p>
      </div>
      <div class="p-news__wrap">
        <div class="p-news__info-wrap">
          <div class="p-news__info">
            <p class="p-news__date c-font-hide c-read-text-color">2020.07.01</p>
            <p class="p-news__tag">更新情報</p>
            <p class="p-news__title c-read-text-color">雑記を追加しました。</p>
          </div>
          <div class="c-read-text-color">+</div>
        </div>
        <p class="p-news__note">「このサイトについて」の雑記を追加しました。</p>
      </div>
    </div>
  </div>
</section>

<section id="note" class="c-section-padding">
  <div class="p-note__content c-content-width">
    <div class="p-note__section-title c-section-title__content">
      <p class="c-section-title__decoration">雑記</p>
      <h3 class="c-section-title c-font-hide">NOTE</h3>
      <div class="p-note__border-line c-border-line--black" data-aos="fade-right"></div>
    </div>
    <div class="p-note__wrap">
      <a href="#" class="p-note__card">
        <img class="p-note__image" src="<%= image_path("note/09.jpg") %>" >
        <p class="p-note__date c-read-text-color c-font-hide">2020.07.01</p>
        <p class="p-note__title c-read-text-color">このサイトについて</p>
      </a>
    </div>
    <div class="p-note__wrap">
      <a href="#" class="p-note__card">
        <img class="p-note__image" src="<%= image_path("note/02.jpg") %>" >
        <p class="p-note__date c-read-text-color c-font-hide">2020.07.01</p>
        <p class="p-note__title c-read-text-color">自己紹介</p>
      </a>
    </div>
    <div class="p-note__wrap">
      <a href="#" class="p-note__card">
        <img class="p-note__image" src="<%= image_path("note/03.jpg") %>" >
        <p class="p-note__date c-read-text-color c-font-hide">2020.07.01</p>
        <p class="p-note__title c-read-text-color">写真はじめました</p>
      </a>
    </div>
    <div class="c-more-button__wrap">
      <a href="<%= notes_path %>" class="c-more-button">
        <p class="c-more-button__text font-hide">READ&nbsp;MORE</p>
        <div class="c-more-button__arrow"></div>
      </a>
    </div>
  </div>
</section>

<section id="photo" class="c-section-padding">
  <div class="p-photo__content c-content-width">
    <div class="p-photo__section-title c-section-title__content">
      <p class="p-photo__title c-section-title__decoration">撮影した写真</p>
      <h3 class="c-section-title c-font-hide">PHOTO</h3>
      <div class="p-photo__border-line c-border-line--black" data-aos="fade-right"></div>
    </div>
    <a href="<%= photos_path %>" class="p-photo__wrap">
      <img class="p-photo__image" src="<%= image_path("photo.jpg") %>" >
      <p class="p-photo__image-text c-font-hide" >GALLERY</p>
    </a>
  </div>
</section>

<section id="contact" class="c-section-padding">
  <div class="p-contact__content c-content-width">
    <div class="p-contact__section-title c-section-title__content">
      <p class="c-section-title__decoration">お問い合わせ</p>
      <h3 class="c-section-title c-font-hide">CONTACT</h3>
      <div class="c-border-line--black" data-aos="fade-right"></div>
    </div>
    <p class="p-contact__read-text">気軽にこちらのSNSをご利用ください。</p>
    <div class="p-contact__wrap">
      <a href="https://twitter.com/nekojekyll" class="p-contact__twitter c-font-hide">Twitter</a>
      <a href="https://www.instagram.com/neko.jekyll/" class="p-contact__instagram c-font-hide">Instagram</a>
    </div>
  </div>
</section>

<footer id="footer">
  <div class="p-footer__content c-content-width">
    <p class="p-footer__copyright c-font-hide">Copyright © 2020 Ryo T. All Rights Reserved.<p>
    <img class="p-footer__image" src="<%= image_path("cat-icon01.png") %>" >
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatEye.note</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" id="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hind:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>AOS.init();</script>
  </body>
</html>

app/views/note/index.html.erb
<h1 class="c-font-hide">Coming Soon</h1>

app/views/photo/index.html.erb
<h1>Photo#index</h1>
<p>Find me in app/views/photo/index.html.erb</p>